### PR TITLE
Allow passing literal JSON strings instead of file paths

### LINKED ISSUE #109: Support for inline configuration strings
Sometimes when productionalizing taps and targets executions it gets inconvenient having to rely on an actual configuration file stored in the system, and instead it would be much easier to be able to pass such config as a JSON string in the command line parameters.
So something like this

```bash
tap-mysql --config '{"host": "mysql-host.com", "port": "3306", "user": "$USR_PROD", "password": "$PWD_PROD"}'
```

One simple hack for supporting that would be changing [this line](https://github.com/singer-io/singer-python/blob/master/singer/utils.py#L107) to something like this

```python
def load_json(path):
  try:
      inline_config = json.loads(myjson)
  except ValueError as e:
    with open(path) as fil:
      return json.load(fil)
  return inline_config
```

### PR DESCRIPTION
**Pull request by dcereijodo**
Extended `load_json` function in the `utils` to accept literal JSON strings instead of file paths. `load_json` will try to interpret the input string as JSON and fallback to interpret it as a file path when JSON parsing fails.

Closes #109

### CODE REVIEW

**Comment by cmerrick** [comment]
You did it @dcereijodo!

Thank you for signing the Singer Contribution License Agreement.

**Comment by Jude188** [comment]
Looks really good! Any chance this can get merged? @cmerrick

**Comment by Jude188** [comment]
@cmerrick

**Comment by dcereijodo** [comment]
Closing this as it doesn't look like it's getting merged.

**Pull request closed without merging**
